--- 
javascripts: 
- base: 
  - prototype
  - effects
  - controls
  - slider
  - dragdrop
  - tagging
  - itembrowser
  - in_place_completer
  - cookies
  - application
stylesheets: 
- base: 
  - winnow
  - tables
  - slider
  - scaffold
