default:
   fi_ajax_single_tag_filter, fi_ajax_single_feed_filter, fi_ajax_single_text_filter

fi_index:
   uri: /feed_items.js
   session_data:
      user: 1
   
fi_ajax_single_tag_filter:
    uri: /feed_items.js?order=date&direction=desc&mode=all&tag_ids=32
    session_data:
      user: 1
    
fi_ajax_single_feed_filter:
    uri: /feed_items.js?order=date&direction=desc&mode=all&feed_ids=771
    session_data:
      user: 1

fi_ajax_single_text_filter:
    uri: /feed_items.js?order=date&direction=desc&mode=all&text_filter=ruby
    session_data:
      user: 1
