#!/usr/bin/env ruby
begin
  load File.expand_path(File.dirname(__FILE__) + "/../vendor/gems/cucumber-0.1.14/bin/cucumber")
rescue LoadError
  require "rubygems"
  load File.join(Gem.bindir, "cucumber")
end