#!/usr/bin/env ruby
begin
  load File.expand_path(File.dirname(__FILE__) + "/../vendor/gems/cucumber-0.2.3/bin/cucumber")
rescue LoadError => e
  raise unless e.to_s =~ /cucumber/  
  require "rubygems"
  load File.join(Gem.bindir, "cucumber")
end